### ISSUE TITLE
undefined method `length' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by maxvoltar** [zroger/jekyll-minimagick#19]
[warning: noob] Have a pretty vanilla Jekyll that was running fine until I tried adding `jekyll-minimagick`. Here's the error I keep bumping into:

```
1: from /Users/tim/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/lib/jekyll/static_file.rb:161:in `url' /Users/tim/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/lib/jekyll/static_file.rb:148:in `cleaned_relative_path': undefined method `length' for nil:NilClass (NoMethodError)
```

Files I've changed:

* Created `_plugins/bundler.rb`
* Created `_plugins/my-plugin.rb`
* Added `gem "jekyll-minimagick"` to `:jekyll_plugins` in my Gemfile
* Added this bit to the bottom of `_config.yml`:

```
mini_magick:
  thumbnail:
    source: photos/original
    destination: photos/thumbnail
    resize: "640x640"
  tint:
    source: photos/original
    destination: photos/tint
    resize: "1x1"
```

Anyone has any thoughts? Is this a bug or human error?
